### ISSUE TITLE
/etc/cgroup.json 其他系统是否存在

### ISSUE THREAD

**Issue by CraKeyBoy** [xy815661276/Android-Container#4]
修改安卓操作系统的/etc/cgroup.json文件 , 这个文件只在 PixelExperience os 里存在吗？

**Comment by xy815661276** [comment]
自行添加

**Comment by CraKeyBoy** [comment]
查了资料，发现 android 10 系统以后才有这个文件。android 9 以下的没有这个文件。

**Comment by xy815661276** [comment]
直接用我给的配置文件。

**Comment by CraKeyBoy** [comment]
android 10 以下这个配置不生效
